baseURL = "https://clayyount.com/"
languageCode = "en-us"
title = "My Comic"
[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]
[permalinks]
comic = "/:section/:year/:month/:day/:title/"
blog = "/:section/:year/:month/:day/:title/"